/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   on_expose.c                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: abelov <abelov@student.42london.com>       +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/03/10 22:25:05 by abelov            #+#    #+#             */
/*   Updated: 2025/03/28 17:28:28 by fsmyth           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../../include/cub3d.h"

/**
 * The XSync function flushes the output buffer and then waits until
 * all requests have been received and processed by the X server.
 * Any errors generated must be handled by the error handler.
 * For each protocol error received by Xlib, XSync calls the client
 * application's error handling routine (see section 11.8.2).
 *
 * Any events generated by the server are enqueued into the library's
 * event queue.
 */
void on_expose(t_info *app)
{
	mlx_put_image_to_window(app->mlx, app->root,
							app->canvas, app->clip_x_origin,
							app->clip_y_origin);
	draw_mmap(app);
	// print_ascii_mmap(app->map, app->player);
}
